[Network]
Address = ':50001'

[Server]
Name = ''
ShutdownMessage = 'Server closed.'
AuthEnabled = false
JoinMessage = ''
QuitMessage = ''

[World]
SaveData = true
Folder = 'assets/kek'

[Players]
MaxCount = 0
MaximumChunkRadius = 32
SaveData = true
Folder = 'assets/players'

[Resources]
AutoBuildPack = true
Folder = 'assets/resources'
Required = true

[Moyai]
Tebex = ''
Whitelisted = false
Season = 1
Start = 'Edit this!'
End = 'Edit this!'

[Proxy]
Enabled = true

[Oomph]
Enabled = true