[Network]
Address = ':50001'

[Server]
Name = ''
ShutdownMessage = 'Server closed.'
AuthEnabled = true
JoinMessage = ''
QuitMessage = ''

[World]
SaveData = true
Folder = 'assets/world'

[Players]
MaxCount = 0
MaximumChunkRadius = 32
SaveData = true
Folder = 'assets/players'

[Resources]
AutoBuildPack = true
Folder = 'assets/resources'
Required = true

[Moyai]
Tebex = ''
Whitelisted = true
Season = 1
Start = 'Edit this!'
End = 'Edit this!'
