[Network]
Address = ':19133'

[Server]
Name = ''
ShutdownMessage = 'Server closed.'
AuthEnabled = false
JoinMessage = ''
QuitMessage = ''

[World]
SaveData = true
Folder = "assets/worlds/overworld"

[Nether]
Folder = "assets/worlds/nether"

[End]
Folder = "assets/worlds/end"

[Players]
MaxCount = 0
MaximumChunkRadius = 16
SaveData = true
Folder = "assets/players"

[Resources]
AutoBuildPack = true
Folder = 'assets/resources'
Required = true

[Moyai]
Tebex = ''
Whitelisted = false
Season = 1
Start = '5/24/24'
End = '6/2/24'

[Proxy]
Enabled = false

[Oomph]
Enabled = false