[Network]
Address = '192.168.2.157:19132'

[Server]
Name = 'Dragonfly Server'
ShutdownMessage = 'Server closed.'
AuthEnabled = true
JoinMessage = '%v has joined the game'
QuitMessage = '%v has left the game'

[World]
SaveData = true
Folder = 'world'

[Players]
MaxCount = 0
MaximumChunkRadius = 32
SaveData = true
Folder = 'players'

[Resources]
AutoBuildPack = true
Folder = 'resources'
Required = false

[Moyai]
Tebex = ''
Whitelisted = true
Season = 1
Start = 'Edit this!'
End = 'Edit this!'
