[Network]
Address = ':19133'

[Server]
Name = ''
ShutdownMessage = 'Server closed.'
AuthEnabled = false
JoinMessage = ''
QuitMessage = ''

[World]
SaveData = true
Folder = "assets/hcfworld"

[Players]
MaxCount = 0
MaximumChunkRadius = 16
SaveData = true
Folder = "assets/players"

[Resources]
AutoBuildPack = true
Folder = 'assets/resources'
Required = true

[Moyai]
Tebex = ''
Whitelisted = false
Season = 1
Start = 'Edit this!'
End = 'Edit this!'

[Proxy]
Enabled = false

[Oomph]
Enabled = true